import { useNavigate } from 'react-router-dom';
import { ListChecks, Users, Building2, Briefcase, Calendar, ArrowRight } from 'lucide-react';
import { useEntityList } from '@/lib/useEntityList';
import PageHeader from '@/components/PageHeader';
import Loading from '@/components/Loading';
import EmptyState from '@/components/EmptyState';
import StatusBadge from '@/components/StatusBadge';

function formatGenerated(dateStr) {
  if (!dateStr) return '—';
  const date = new Date(dateStr);
  const now = new Date();
  const isToday = date.toDateString() === now.toDateString();
  if (isToday) return 'Today';
  return date.toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' });
}

export default function Shortlists() {
  const navigate = useNavigate();
  const { data: shortlists, loading } = useEntityList('Shortlist', { sort: '-created_date' });

  return (
    <div className="space-y-6">
      <PageHeader title="Shortlists" description="Every shortlist generated by Deema AI. Review candidates and publish to make them visible to startups." />

      {loading ? <Loading /> : (shortlists || []).length === 0 ? (
        <EmptyState
          icon={ListChecks}
          title="No shortlists yet"
          description="Run Deema AI analysis from the Applications page to generate your first shortlist."
        />
      ) : (
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">
          {(shortlists || []).map(s => (
            <div key={s.id} className="flex flex-col rounded-2xl border border-border bg-white p-5 shadow-sm transition hover:shadow-md">
              <div className="flex items-start justify-between gap-3">
                <div className="flex items-center gap-2.5">
                  <div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-violet-50 text-violet-600">
                    <Building2 className="h-4.5 w-4.5" />
                  </div>
                  <div>
                    <p className="text-xs font-medium uppercase tracking-wider text-muted-foreground">Startup</p>
                    <p className="text-sm font-semibold text-foreground">{s.startup_name || '—'}</p>
                  </div>
                </div>
                <StatusBadge status={s.status || 'draft'} />
              </div>

              <div className="mt-4 flex items-center gap-2.5">
                <div className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-muted/60 text-muted-foreground">
                  <Briefcase className="h-4 w-4" />
                </div>
                <div>
                  <p className="text-xs font-medium uppercase tracking-wider text-muted-foreground">Internship</p>
                  <p className="text-sm font-medium text-foreground">{s.internship_title || '—'}</p>
                </div>
              </div>

              <div className="mt-4 flex items-center justify-between rounded-xl bg-muted/30 px-3.5 py-2.5">
                <div className="flex items-center gap-1.5 text-sm text-muted-foreground">
                  <Users className="h-4 w-4" /> Top Candidates
                </div>
                <span className="text-sm font-semibold text-foreground">{s.candidates?.length ?? s.top_count ?? 0}</span>
              </div>

              <div className="mt-2 flex items-center justify-between rounded-xl bg-muted/30 px-3.5 py-2.5">
                <div className="flex items-center gap-1.5 text-sm text-muted-foreground">
                  <Calendar className="h-4 w-4" /> Generated
                </div>
                <span className="text-sm font-semibold text-foreground">{formatGenerated(s.created_date)}</span>
              </div>

              <button
                onClick={() => navigate(`/admin/shortlists/${s.id}`)}
                className="mt-5 inline-flex items-center justify-center gap-1.5 rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-violet-700"
              >
                View Shortlist <ArrowRight className="h-4 w-4" />
              </button>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
