import { useEffect, useState } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import { ArrowLeft, Sparkles, ExternalLink, GraduationCap, Building2, Briefcase, Calendar, Award, Loader2, CheckCircle2, Check, X } from 'lucide-react';
import { db } from '@/api/base44Client';
import PageHeader from '@/components/PageHeader';
import Loading from '@/components/Loading';
import EmptyState from '@/components/EmptyState';
import StatusBadge from '@/components/StatusBadge';
import { useToast } from '@/components/ui/use-toast';

export default function ShortlistDetail() {
  const { id } = useParams();
  const navigate = useNavigate();
  const { toast } = useToast();
  const [shortlist, setShortlist] = useState(null);
  const [loading, setLoading] = useState(true);
  const [publishing, setPublishing] = useState(false);
  const [decidingId, setDecidingId] = useState(null);

  const load = () => {
    setLoading(true);
    db.entities.Shortlist.get(id)
      .then(setShortlist)
      .catch(() => setShortlist(null))
      .finally(() => setLoading(false));
  };

  useEffect(() => { load(); }, [id]);

  const candidateStatus = (c) => c.status || 'under_review';
  const allReviewed = (shortlist?.candidates || []).length > 0 &&
    (shortlist.candidates || []).every(c => candidateStatus(c) !== 'under_review');

  const handleDecision = async (candidate, decision) => {
    if (!shortlist) return;
    const candidateKey = candidate.application_id || candidate.candidate_name;
    setDecidingId(candidateKey);
    try {
      const updatedCandidates = (shortlist.candidates || []).map((c) =>
        (c.application_id || c.candidate_name) === candidateKey ? { ...c, status: decision } : c
      );
      const updated = await db.entities.Shortlist.update(shortlist.id, { candidates: updatedCandidates });
      if (candidate.application_id) {
        await db.entities.Application.update(candidate.application_id, { status: decision });
      }
      setShortlist(updated);
      toast({ title: decision === 'approved' ? 'Candidate approved' : 'Candidate rejected' });
    } catch {
      toast({ title: 'Failed to update candidate status', variant: 'destructive' });
    } finally {
      setDecidingId(null);
    }
  };

  const handlePublish = async () => {
    if (!shortlist) return;
    if (!allReviewed) return;
    setPublishing(true);
    try {
      const approvedCandidates = (shortlist.candidates || []).filter(c => candidateStatus(c) === 'approved');
      const updatedCandidates = (shortlist.candidates || []).map((c) =>
        candidateStatus(c) === 'approved' ? { ...c, status: 'shortlisted' } : c
      );
      const updated = await db.entities.Shortlist.update(shortlist.id, { status: 'published', candidates: updatedCandidates });
      await Promise.all(
        approvedCandidates
          .filter(c => c.application_id)
          .map(c => db.entities.Application.update(c.application_id, { status: 'shortlisted' }))
      );
      toast({ title: 'Shortlist published', description: 'Approved candidates are now visible to the startup and students have been notified of their status.' });
      setShortlist(updated);
    } catch {
      toast({ title: 'Failed to publish shortlist', variant: 'destructive' });
    } finally {
      setPublishing(false);
    }
  };

  if (loading) return <Loading />;

  if (!shortlist) {
    return (
      <div className="space-y-6">
        <PageHeader title="Shortlist" description="Review AI-shortlisted candidates." />
        <EmptyState icon={Award} title="Shortlist not found" description="This shortlist may have been removed or re-analyzed." />
        <button onClick={() => navigate('/admin/shortlists')} className="inline-flex items-center gap-2 rounded-xl border border-border bg-white px-4 py-2 text-sm font-medium hover:bg-muted">
          <ArrowLeft className="h-4 w-4" /> Back to Shortlists
        </button>
      </div>
    );
  }

  const candidates = shortlist.candidates || [];

  return (
    <div className="space-y-6">
      <PageHeader title={shortlist.internship_title || 'Shortlist'} description="AI-shortlisted candidates generated by Deema.">
        <Link to="/admin/shortlists" className="inline-flex items-center gap-1.5 rounded-xl border border-border bg-white px-3.5 py-2 text-xs font-semibold text-foreground hover:bg-muted">
          <ArrowLeft className="h-3.5 w-3.5" /> All Shortlists
        </Link>
      </PageHeader>

      <div className="rounded-2xl border border-border bg-white p-5 shadow-sm">
        <div className="grid grid-cols-1 gap-4 sm:grid-cols-4">
          <div className="flex items-center gap-2.5">
            <div className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-violet-50 text-violet-600"><Building2 className="h-4 w-4" /></div>
            <div>
              <p className="text-xs text-muted-foreground">Startup</p>
              <p className="text-sm font-semibold text-foreground">{shortlist.startup_name || '—'}</p>
            </div>
          </div>
          <div className="flex items-center gap-2.5">
            <div className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-violet-50 text-violet-600"><Briefcase className="h-4 w-4" /></div>
            <div>
              <p className="text-xs text-muted-foreground">Internship</p>
              <p className="text-sm font-semibold text-foreground">{shortlist.internship_title || '—'}</p>
            </div>
          </div>
          <div className="flex items-center gap-2.5">
            <div className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-violet-50 text-violet-600"><Calendar className="h-4 w-4" /></div>
            <div>
              <p className="text-xs text-muted-foreground">Generated</p>
              <p className="text-sm font-semibold text-foreground">{shortlist.created_date ? new Date(shortlist.created_date).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' }) : '—'}</p>
            </div>
          </div>
          <div className="flex items-center gap-2.5">
            <div className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-violet-50 text-violet-600"><Award className="h-4 w-4" /></div>
            <div>
              <p className="text-xs text-muted-foreground">Status</p>
              <StatusBadge status={shortlist.status || 'draft'} />
            </div>
          </div>
        </div>
      </div>

      <div className="space-y-3">
        <p className="text-sm font-semibold text-foreground">Candidates ({candidates.length})</p>
        {candidates.length === 0 ? (
          <EmptyState icon={Award} title="No candidates in this shortlist" />
        ) : (
          <div className="space-y-3">
            {candidates.map((c, idx) => {
              const status = candidateStatus(c);
              const candidateKey = c.application_id || c.candidate_name || idx;
              const isDeciding = decidingId === (c.application_id || c.candidate_name);
              const isPublished = shortlist.status === 'published';
              return (
                <div key={candidateKey} className="rounded-2xl border border-border bg-white p-5 shadow-sm">
                  <div className="flex flex-wrap items-start justify-between gap-3">
                    <div>
                      <div className="flex flex-wrap items-center gap-2">
                        <p className="font-semibold text-foreground">{c.candidate_name}</p>
                        <StatusBadge status={status} />
                      </div>
                      <div className="mt-1 flex flex-wrap items-center gap-x-4 gap-y-1 text-xs text-muted-foreground">
                        {c.student_university && (
                          <span className="inline-flex items-center gap-1"><GraduationCap className="h-3.5 w-3.5" /> {c.student_university}</span>
                        )}
                        {c.student_major && <span>{c.student_major}</span>}
                      </div>
                    </div>
                    {c.resume_url && (
                      <a href={c.resume_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1.5 text-sm font-medium text-violet-600 hover:text-violet-700">
                        <ExternalLink className="h-4 w-4" /> Resume
                      </a>
                    )}
                  </div>

                  {c.ai_summary && (
                    <div className="mt-3 rounded-xl bg-violet-50/60 p-3.5 ring-1 ring-inset ring-violet-600/10">
                      <div className="mb-1 flex items-center gap-1.5 text-xs font-semibold text-violet-700">
                        <Sparkles className="h-3.5 w-3.5" /> Deema AI Summary
                      </div>
                      <p className="text-sm text-foreground/85">{c.ai_summary}</p>
                    </div>
                  )}

                  {!isPublished && (
                    <div className="mt-4 flex justify-end gap-2">
                      <button
                        onClick={() => handleDecision(c, 'rejected')}
                        disabled={isDeciding || status !== 'under_review'}
                        className="inline-flex items-center gap-1.5 rounded-xl border border-rose-200 bg-white px-3.5 py-2 text-xs font-semibold text-rose-600 transition hover:bg-rose-50 disabled:cursor-not-allowed disabled:opacity-50"
                      >
                        <X className="h-3.5 w-3.5" /> Reject
                      </button>
                      <button
                        onClick={() => handleDecision(c, 'approved')}
                        disabled={isDeciding || status !== 'under_review'}
                        className="inline-flex items-center gap-1.5 rounded-xl bg-emerald-600 px-3.5 py-2 text-xs font-semibold text-white transition hover:bg-emerald-700 disabled:cursor-not-allowed disabled:opacity-50"
                      >
                        <Check className="h-3.5 w-3.5" /> Approve
                      </button>
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        )}
      </div>

      <div className="flex flex-col items-end gap-2">
        {shortlist.status === 'published' ? (
          <span className="inline-flex items-center gap-2 rounded-xl bg-emerald-50 px-5 py-2.5 text-sm font-semibold text-emerald-700 ring-1 ring-inset ring-emerald-600/20">
            <CheckCircle2 className="h-4 w-4" /> Published
          </span>
        ) : (
          <>
            <button
              onClick={handlePublish}
              disabled={publishing || candidates.length === 0 || !allReviewed}
              className="inline-flex items-center gap-2 rounded-xl bg-violet-600 px-6 py-3 text-sm font-semibold text-white shadow-lg shadow-violet-500/25 transition hover:bg-violet-700 disabled:cursor-not-allowed disabled:opacity-60"
            >
              {publishing ? <Loader2 className="h-4 w-4 animate-spin" /> : <Award className="h-4 w-4" />}
              Publish Shortlist
            </button>
            {!allReviewed && (
              <p className="text-xs text-muted-foreground">Please review all candidates before publishing this shortlist.</p>
            )}
          </>
        )}
      </div>
    </div>
  );
}
